WebApp/Controllers/TopicController.cs
using AutoMapper;
using Lib.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection.XmlEncryption;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC.ViewModels;
using NuGet.Packaging;
using NuGet.Protocol;
using System;

namespace MVC.Controllers
{
    [Authorize]
    public class TopicController : Controller
    {

        private readonly RwaContext _context;
        private readonly IConfiguration _configuration;
        private readonly IMapper _mapper;


        public TopicController(RwaContext context, IConfiguration configuration, IMapper mapper)
        {
            _context = context;
            _configuration = configuration;
            _mapper = mapper;
        }



        // GET: TopicController
        public ActionResult Index(SearchVM searchVm)
        {
            IQueryable<Topic> topics = _context
                .Topics
                .Include(x => x.Category)
                .Include(x => x.Posts)
                .Include(x => x.Tags).ThenInclude(x => x.Topics);
            if (!string.IsNullOrEmpty(searchVm.Query))
            {
                topics = topics.Where(x => x.Title.Contains(searchVm.Query));
            }
            if (searchVm.OrderBy is not null)
            {
                switch (searchVm.OrderBy.ToLower())
                {
                    case "date":
                        topics = topics.OrderBy(x => x.CreatedAt);
                        break;
                    case "title":
                        topics = topics.OrderBy(x => x.Title);
                        break;
                    case "category":
                        topics = topics.OrderBy(x => x.Category.Name);
                        break;
                    case "posts":
                        topics = topics.OrderBy(x => x.Posts.Count);
                        break;
                    default:
                        topics = topics.OrderBy(x => x.Id);
                        break;
                }
            }
            var filteredCount = topics.Count();
            // BEGIN PAGER
            var expandPages = _configuration.GetValue<int>("Paging:ExpandPages");
            searchVm.LastPage = (int)Math.Ceiling(1.0 * filteredCount / searchVm.Size);
            searchVm.FromPager = searchVm.Page > expandPages ?
              searchVm.Page - expandPages :
              1;
            searchVm.ToPager = (searchVm.Page + expandPages) < searchVm.LastPage ?
              searchVm.Page + expandPages :
              searchVm.LastPage;
            // END PAGER

            topics = topics.Skip((searchVm.Page - 1) * searchVm.Size).Take(searchVm.Size);

            List<TopicVM> topicVMs = _mapper.Map<List<TopicVM>>(topics.ToList());
            searchVm.Topics = topicVMs;
            return View(searchVm);
        }

        // GET: TopicController/Details/5
        public ActionResult Details(int id, PostSearchVM postsearch)
        {
            string jwt = User.FindFirst("JWT")?.Value;
            string username = HttpContext.User.Identity.Name;
            var user = _context.Users.FirstOrDefault(x => x.Username == username);
            ViewBag.UserRatedPosts = _context.Ratings.Where(x => x.UserId == user.Id).Where(r => r.PostId.HasValue).ToDictionary(r => r.PostId.Value, r => r.Score);
            ViewBag.JWT = jwt;
            var dbtopic = _context
                .Topics
                .Include(x => x.Category)
                .Include(x => x.Posts)
                .Include(x => x.Tags).ThenInclude(x => x.Topics).FirstOrDefault(x => x.Id == id);


            IQueryable<Post> postss = _context.Posts.Include(x => x.Ratings).Include(x => x.Topic).Include(x => x.User).Where(x => x.TopicId == id);

            if (postsearch.OrderBy is not null)
            {
                switch (postsearch.OrderBy.ToLower())
                {
                    case "date":
                        postss = postss.OrderByDescending(x => x.PostedAt);
                        break;
                    case "content":
                        postss = postss.OrderBy(x => x.Content);
                        break;
                    case "content-length":
                        postss = postss.OrderBy(x => x.Content);
                        break;
                    case "score":
                        postss = postss.OrderByDescending(x => x.Ratings.Count > 0 ? (int)Math.Round((decimal)x.Ratings.Average(r => r.Score)) : 0);
                        break;
                    default:
                        postss = postss.OrderBy(x => x.Id);
                        break;
                }
            }


            var filteredCount = postss.Count();
            // BEGIN PAGER
            var expandPages = _configuration.GetValue<int>("Paging:ExpandPages");
            postsearch.LastPage = (int)Math.Ceiling(1.0 * filteredCount / postsearch.Size);
            postsearch.FromPager = postsearch.Page > expandPages ?
              postsearch.Page - expandPages :
              1;
            postsearch.ToPager = (postsearch.Page + expandPages) < postsearch.LastPage ?
              postsearch.Page + expandPages :
              postsearch.LastPage;
            // END PAGER

            postss = postss.Skip((postsearch.Page - 1) * postsearch.Size).Take(postsearch.Size);

            List<PostVM> postVMs = _mapper.Map<List<PostVM>>(postss.ToList());

            postsearch.Posts = postVMs;
            postsearch.Topic = _mapper.Map<TopicVM>(dbtopic);

            PostDTO postvm = new PostDTO
            {
                TopicId = dbtopic.Id,
                UserId = user.Id,
            };
            ViewBag.PostVM = postvm;
            Console.WriteLine(username);
            Console.WriteLine(user);
            return View(postsearch);
        }

        // GET: TopicController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Tags = GetTagsListItems();
            ViewBag.Categories = GetCatsListItems();
            return View();
        }

        public List<SelectListItem> GetCatsListItems()
        {
            var genreListItemsJson = HttpContext.Session.GetString("CatsListItems");

            List<SelectListItem> genreListItems;
            if (genreListItemsJson == null)
            {
                genreListItems = _context.Categories
                    .Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }).ToList();

                HttpContext.Session.SetString("CatsListItems", genreListItems.ToJson());
            }
            else
            {
                genreListItems = genreListItemsJson.FromJson<List<SelectListItem>>();
            }

            return genreListItems;
        }

        private List<SelectListItem> GetTagsListItems()
        {
            var genreListItemsJson = HttpContext.Session.GetString("TagListItems");

            List<SelectListItem> genreListItems;
            if (genreListItemsJson == null)
            {
                genreListItems = _context.Tags
                    .Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }).ToList();

                HttpContext.Session.SetString("TagListItems", genreListItems.ToJson());
            }
            else
            {
                genreListItems = genreListItemsJson.FromJson<List<SelectListItem>>();
            }

            return genreListItems;
        }


        // POST: TopicController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(TopicVM topic, string action)
        {
            try
            {
                if (_context.Topics.Any(x => x.Title == topic.Title))
                {
                    ViewBag.ErrorMessage = "Topic with this title already exists.";
                    ViewBag.Tags = GetTagsListItems();
                    ViewBag.Categories = GetCatsListItems();
                    return View("Create");
                }

                if (!ModelState.IsValid)
                {
                    ViewBag.Tags = GetTagsListItems();
                    ViewBag.Categories = GetCatsListItems();
                    ModelState.AddModelError("", "Failed to create a topic");
                    return View();
                }
                var tags = topic.TagIds.ToList();
                var dbtopic = _mapper.Map<Topic>(topic);
                _context.Topics.Add(dbtopic);
                _context.SaveChanges();

                if (action == "Create")
                {
                    return RedirectToAction(nameof(Index));

                }
                return RedirectToAction("Create");

            }
            catch
            {
                return View();
            }
        }

        // GET: TopicController/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            ViewBag.Tags = GetTagsListItems();
            ViewBag.Categories = GetCatsListItems();

            var dbtopic = _context.Topics.FirstOrDefault(x => x.Id == id);
            var category = _context.Categories.FirstOrDefault(x => x.Id == dbtopic.CategoryId);

            var tagids = dbtopic.Tags.Select(x => x.Id);

            var topicvm = _mapper.Map<TopicVM>(dbtopic);
            return View(topicvm);
        }

        // POST: TopicController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id, TopicVM topicVM)
        {
            try
            {
               

WebApp/Views/Topic/Create.cshtml
@model MVC.ViewModels.TopicVM

@{
    ViewData["Title"] = "Create";
  
}

<h1>Create</h1>
@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger">@ViewBag.ErrorMessage</div>
}
<h4>Topic</h4>
<hr />
<div>
    <a class="btn btn-outline-primary" asp-action="Index">Back to List  </a>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-select" >
                    <option value="">(not selected)</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Tags</label>
                @foreach (var tag in ViewBag.Tags as List<SelectListItem>)
                {
                    <div class="form-check">
                        <input class="form-check-input"
                               type="checkbox"
                               name="TagIds"
                               value="@tag.Value"
                               id="tag_@tag.Value"/>
                        <label class="form-check-label" for="tag_@tag.Value">
                            @tag.Text
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <input type="submit" name="action" value="Create" class="btn btn-primary" />
                <input type="submit" name="action" value="Create Another" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

WebApp/Views/Topic/Delete.cshtml
@model MVC.ViewModels.TopicVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publish_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publish_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagNames)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagNames)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostsCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostsCount)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-outline-primary" asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Topic/Details.cshtml
@using MVC.ViewModels
@using Newtonsoft.Json
@model MVC.ViewModels.PostSearchVM

@{
    ViewData["Title"] = Model.Topic.Title;
    var posts = Model.Posts;
    var jwt = @Html.Raw(JsonConvert.SerializeObject(ViewBag.JWT));
}

<h1>@Model.Topic.Title</h1>

<div class="mb-3 topic" data-topic-id="@Model.Topic.Id">
    <p><strong>Category:</strong> @Model.Topic.CategoryName</p>
    <p><strong>Tags:</strong> @string.Join(", ", Model.Topic.TagNames)</p>
    <p><strong>Posted on:</strong> @Model.Topic.Publish_Date?.ToString("g")</p>
    <p>@Model.Topic.Description</p>
</div>

<hr />
<form asp-action="Details" method="GET">
    <div class="row">
        <nav>
            <ul class="pagination">
                @for (int i = Model.FromPager; i <= Model.ToPager; i++)
                {
                    var linkText = @i.ToString();
                    if (i != 1 && i == Model.FromPager)
                    {
                        linkText = "«";
                    }
                    else if (i != Model.LastPage && i == Model.ToPager)
                    {
                        linkText = "»";
                    }

                    var linkClass = "page-item";
                    if (i == Model.Page)
                    {
                        linkClass = "page-item active";
                    }
                    <li class="@linkClass">
                        @Html.ActionLink(
                                 @linkText,
                                 "Details",
                                 new
                                 {
                                     orderby = Model.OrderBy,
                                     page = i,
                                     size = Model.Size
                                 },
                                 new { @class = "page-link" })
                    </li>
                }
            </ul>
        </nav>
        <div class="col-auto">
            <label class="form-label mt-1">Sort by:</label>
        </div>
        <div class="col-auto">
            <select asp-for="OrderBy" class="form-select">
                <option value="id">(default)</option>
                <option>Date</option>
                <option>Content</option>
                <option>Content-Length</option>
                <option>Score</option>
            </select>
        </div>
        <div class="col-auto">
            <input type="submit" value="Go" class="btn btn-primary" />
        </div>
    
    </div>
</form>
<h3>Posts</h3>

@if (posts != null && posts.Any())
{
    foreach (var post in posts)
    {
        <div class="card mb-3 post" data-post-id="@post.Id">
            <div class="card-body">
                <p>@post.Content</p>
                <p class="text-muted mb-0">
                    Posted by <strong>@post.CreatorUsername</strong> on @post.Published_Date?.ToString("g")
                    | <strong>Score:</strong> @post.Score
                </p>
            </div>
            <div class="star-rating" data-selected="0" data-post-id="@post.Id">
                @for (int i = 1; i <= 5; i++)
                {
                    <i class="fa fa-star star" aria-hidden="true" data-value="@i"></i>
                }
            </div>
        </div>
    }
}
else
{
    <p>No posts yet. Be the first to contribute!</p>
}


<hr />

<!-- New Post Form -->
<h4>Add Your Post</h4>
<form id="postform">
    <input type="hidden" name="TopicId" value="@Model.Topic.Id" />

    <div class="form-group mb-3">
        <textarea name="Content" class="form-control" id="contenttxt" rows="4" required placeholder="Share your thoughts..."></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Post</button>
</form>



@section Scripts {

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <script>
         const jwt = @Html.Raw(JsonConvert.SerializeObject(ViewBag.JWT));
         const postVM = @Html.Raw(JsonConvert.SerializeObject(ViewBag.PostVM));
         const userRatedPosts = @Html.Raw(Json.Serialize(ViewBag.UserRatedPosts));
         $(document).ready(function () {
            console.log(jwt);
            $('.post').each(function () {
            const postId = $(this).data('post-id');
            const userRating = userRatedPosts[postId];
            console.log(postVM);
            if (userRating) {
                const stars = $(this).find('.star');
                stars.each(function (index) {
                    if (index < userRating) {
                        $(this).addClass('filled');
                    }
                    $(this).addClass('locked');
                });
            }
            });
             $("#postform").on('submit', function (e) {
                e.preventDefault();
                const postcontent = $('#contenttxt').val();
                postVM.Content = postcontent;
                $.ajax({
                    method: "POST",
                    url: "http://localhost:8080/api/Post/Post",
                    data: JSON.stringify(postVM),
                    headers: { "Authorization": `Bearer ${jwt}` },
                    contentType: 'application/json'
                }).done(function (response){location.reload();})
                  .fail(function (err){alert("didnt work");});
            });

            $(".star").on("click", function () {
                if ($(this).hasClass("locked")) return;
                const rating = $(this).data("value");
                const postId = $(this).closest(".post").data("post-id");
                const usersname = $("#usersname").text();
                let postData = {
                    PostId: postId,
                    UserName: usersname,
                    Score: rating}
                console.log(postData);
                $.ajax({
                    method: "POST",
                    url: "http://localhost:8080/api/Rating/Post",
                    data: JSON.stringify(postData),
                    contentType: 'application/json'
                }).done(function (response){location.reload();})
                  .fail(function (err){alert("didnt work");});
            });
        });


        function lockStars(postId, value) {
            const stars = $(`.post[data-post-id='${postId}'] .star`);
            stars.each(function (index) {
                if (index < value) {
                    $(this).addClass('filled');
                }
                $(this).addClass('locked');
            });
        }
    </script>
}

WebApp/Views/Topic/Edit.cshtml
@model MVC.ViewModels.TopicVM

@{
    ViewData["Title"] = "Create";
  
}

<h1>Edit</h1>

<h4>Topic</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.Categories" class="form-select" >
                    <option value="">(not selected)</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Tags</label>
                @foreach (var tag in ViewBag.Tags as List<SelectListItem>)
                {
                    <div class="form-check">
                        <input class="form-check-input"
                               type="checkbox"
                               name="TagIds"
                               value="@tag.Value"
                               id="tag_@tag.Value"/>
                        <label class="form-check-label" for="tag_@tag.Value">
                            @tag.Text
                        </label>
                    </div>
                }
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-outline-primary" asp-action="Index">Back to List</a>
</div>

WebApp/Views/Topic/Index.cshtml
@model MVC.ViewModels.SearchVM

@{
    ViewData["Title"] = "Topics";
    var user = ViewContext.HttpContext.User;

    bool isadmin = false;
    if (user.IsInRole("Admin"))
    {
        isadmin = true;
    }
}

<h1>Topics</h1>
<form asp-action="Index" method="GET">
    <div class="row">
        <div class="col-8">
            <input asp-for="Query" class="form-control" placeholder="Search topics" />
        </div>
        <div class="col-auto">
            <input type="submit" value="Go" class="btn btn-primary" />
        </div>
        <div class="col-auto">
            <label class="form-label mt-1">Sort by:</label>
        </div>
        <div class="col-auto">
            <select asp-for="OrderBy" class="form-select">
                <option value="id">(default)</option>
                <option>Date</option>
                <option>Title</option>
                <option>Category</option>
                <option>Posts</option>
            </select>
        </div>
        <div class="col-auto">
            <select asp-for="Size" class="form-select">
                <option>10</option>
                <option>20</option>
                <option>50</option>
            </select>
        </div>
    </div>
</form>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].PostsCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].TagNames)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Topics[0].Publish_Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Topics)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostsCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TagNames)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Publish_Date)
                </td>

                @if (isadmin)
                {
                    <td>
                        <a asp-controller="Topic" asp-action="Edit" class="btn btn-sm btn-outline-primary" asp-route-id="@item.Id">Edit</a>
                        <a asp-controller="Topic" asp-action="Details" class="btn btn-sm btn-outline-primary" asp-route-id="@item.Id">Details</a>
                        <a asp-controller="Topic" asp-action="Delete" class="btn btn-sm btn-danger" asp-route-id="@item.Id">Delete</a>
                        @* @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }) *@
                    </td>
                }
                else
                {
                    <td>
                        <a asp-controller="Topic" asp-action="Details" class="btn btn-sm btn-outline-primary" asp-route-id="@item.Id">Details</a>
                        @* @Html.ActionLink("Go to Topic", "Details", new { id = item.Id }) *@
                    </td>

                }
            </tr>
        }
    </tbody>
</table>

<nav>
    <ul class="pagination">
        @for (int i = Model.FromPager; i <= Model.ToPager; i++)
        {
            var linkText = @i.ToString();
            if (i != 1 && i == Model.FromPager)
            {
                linkText = "«";
            }
            else if (i != Model.LastPage && i == Model.ToPager)
            {
                linkText = "»";
            }

            var linkClass = "page-item";
            if (i == Model.Page)
            {
                linkClass = "page-item active";
            }
            <li class="@linkClass">
                @Html.ActionLink(
                         @linkText,
                         "Index",
                         new
                         {
                             q = Model.Query,
                             orderby = Model.OrderBy,
                             page = i,
                             size = Model.Size
                         },
                         new { @class = "page-link" })
            </li>
        }
    </ul>
</nav>