WebApp/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/CategoryController.cs
using AutoMapper;
using Lib.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.ViewModels;
using System.Data.Common;

namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly RwaContext _context;
        private readonly IMapper _mapper;


        public CategoryController(RwaContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: CategoryController
        public ActionResult Index()
        {
            var categories = _context.Categories.Include(x => x.Topics).Select(x => _mapper.Map<CategoryVM>(x)).ToList();
            return View(categories);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var dbcategory = _context.Categories.Include(x => x.Topics).FirstOrDefault(x => x.Id == id);
            var categoryvm = _mapper.Map<CategoryVM>(dbcategory);

            return View(categoryvm);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryVM categoryVm, string action)
        {
            try
            {
                var category = _mapper.Map<Category>(categoryVm);
                if (_context.Categories.Any(x => x.Name == categoryVm.Name))
                {
                    ViewBag.ErrorMessage = "Category with this name already exists.";
                    return View("Create");
                }
                _context.Categories.Add(category);
                _context.SaveChanges();

                if (action == "Create")
                {
                    return RedirectToAction(nameof(Index));

                }
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var dbcategory = _context.Categories.Include(x => x.Topics).FirstOrDefault(x => x.Id == id);
                var category = _mapper.Map<CategoryVM>(dbcategory);
                return View(category);
            }
            catch (Exception)
            {

                return View();
            }
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CategoryVM categoryVM)
        {
            try
            {
                var dbcategory = _context.Categories.Include(x => x.Topics).FirstOrDefault(x => x.Id == id);
                dbcategory.Name = categoryVM.Name;
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var dbcategory = _context.Categories.Include(x => x.Topics).FirstOrDefault(x => x.Id == id);
                var category = _mapper.Map<CategoryVM>(dbcategory);
                return View(category);
            }
            catch
            {
                return View();
            }
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, CategoryVM category)
        {
            try
            {
                var dbcategory = _context.Categories.Include(x => x.Topics).FirstOrDefault(x => x.Id == id);
                _context.Categories.Remove(dbcategory);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Controllers/PostController.cs
using AutoMapper;
using Lib.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using MVC.ViewModels;
using NuGet.Protocol;

namespace MVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {

        private readonly RwaContext _context;
        private readonly IMapper _mapper;


        public PostController(RwaContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: PostController
        [Authorize(Roles = "Admin")]

        public ActionResult Index()
        {
            List<PostVM> posts = _context.Posts.Include(x => x.User).Include(x => x.Ratings).Include(x => x.Topic).ToList().Select(x => _mapper.Map<PostVM>(x)).ToList();
            return View(posts);
        }

        // GET: PostController/Details/5
        [Authorize]

        public ActionResult Details(int id)
        {
            var post = _context.Posts.Include(x => x.Ratings).Include(x => x.Topic).Include(x => x.User).FirstOrDefault(x => x.Id == id);

            if (!HttpContext.User.IsInRole("Admin") && post.User.Username!= User.Identity.Name)
            {
                return Unauthorized();
            }
            var postvm = _mapper.Map<PostVM>(post);
            return View(postvm);
        }

        // GET: PostController/Create
        [Authorize(Roles = "Admin")]

        public ActionResult Create()
        {

            ViewBag.Topics = GetTopicItems();
            ViewBag.Users = GetUsersItems();
            return View();
        }

        private dynamic GetUsersItems()
        {
            var ItemsJson = HttpContext.Session.GetString("UsersListItems");

            List<SelectListItem> itemsList;
            if (ItemsJson == null)
            {
                itemsList = _context.Users
                    .Select(x => new SelectListItem
                    {
                        Text = x.Username,
                        Value = x.Id.ToString()
                    }).ToList();

                HttpContext.Session.SetString("UsersListItems", itemsList.ToJson());
            }
            else
            {
                itemsList = ItemsJson.FromJson<List<SelectListItem>>();
            }

            return itemsList;
        }

        public List<SelectListItem> GetTopicItems()
        {
            var ItemsJson = HttpContext.Session.GetString("TopicListItems");

            List<SelectListItem> itemsList;
            if (ItemsJson == null)
            {
                itemsList = _context.Topics
                    .Select(x => new SelectListItem
                    {
                        Text = x.Title,
                        Value = x.Id.ToString()
                    }).ToList();

                HttpContext.Session.SetString("TopicListItems", itemsList.ToJson());
            }
            else
            {
                itemsList = ItemsJson.FromJson<List<SelectListItem>>();
            }

            return itemsList;
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public ActionResult Create(PostVM postvm,string action)
        {
            try
            {
                var user = _context.Users.FirstOrDefault(x => x.Username == postvm.CreatorUsername);
                var dbpost = _mapper.Map<Post>(postvm);
                _context.Posts.Add(dbpost);
                _context.SaveChanges();

                if (action == "Create")
                {
                    return RedirectToAction(nameof(Index));

                }
                return RedirectToAction("Create");
            }
            catch
            {
                return View();
            }
        }

        private bool? CheckProfanity(string content)
        {
            if (content.Contains("Fuck") || content.Contains("Shit"))
            {
                return false;
            }
            return true;
        }

        // GET: PostController/Edit/5
        [Authorize]

        public ActionResult Edit(int id)
        {
            var dbpost = _context.Posts.Include(x=>x.User).Include(x=>x.Topic).Include(x=>x.Ratings).FirstOrDefault(x => x.Id == id);
            if (!HttpContext.User.IsInRole("Admin") && dbpost.User.Username != User.Identity.Name)
            {
                return Unauthorized();
            }
            var postvm = _mapper.Map<PostVM>(dbpost);
            return View(postvm);
        }

        // POST: PostController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, PostVM postVM)
        {
            try
            {

                var dbpost = _context.Posts.Include(x => x.User).Include(x => x.Topic).Include(x => x.Ratings).FirstOrDefault(x => x.Id == id);
                if (!HttpContext.User.IsInRole("Admin") && dbpost.User.Username != User.Identity.Name)
                {
                    return Unauthorized();
                }
                dbpost.Content = postVM.Content;
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PostController/Delete/5
        [Authorize]

        public ActionResult Delete(int id)
        {
            var dbpost = _context.Posts.Include(x => x.User).Include(x => x.Topic).Include(x => x.Ratings).FirstOrDefault(x => x.Id == id);
            if (!HttpContext.User.IsInRole("Admin") && dbpost.User.Username != User.Identity.Name)
            {
                return Unauthorized();
            }
            var postvm = _mapper.Map<PostVM>(dbpost);
            return View(postvm);
        }

        // POST: PostController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Delete(int id, PostVM postvm)
        {
            try
            {
                var dbpost = _context.Posts.Include(x => x.User).Include(x => x.Topic).Include(x => x.Ratings).FirstOrDefault(x => x.Id == id);
                if (!HttpContext.User.IsInRole("Admin") && dbpost.User.Username != User.Identity.Name)
                {
                    return Unauthorized();
                }
                _context.Posts.Remove(dbpost);
                _context.SaveChanges();

                if (HttpContext.User.IsInRole("Admin"))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return GetByUsersString(User.Identity.Name);
                }
            }
            catch
            {
                return View();
            }
        }
        public ActionResult GetByUsers(int id)
        {
            var dbposts = _context.Posts.Where(x => x.UserId == id);
            var user = _context.Users.FirstOrDefault(x => x.Id == id);
            var posts = dbposts.Include(x => x.Topic).Include(x => x.Ratings).Select(x => _mapper.Map<PostVM>(x));
            return View(posts);
        }


        public ActionResult GetByUsersString(string username)
        {
            var dbposts = _context.Posts.Where(x => x.User.Username == username);
            var user = _context.Users.FirstOrDefault(x => x.Username == username);
            ViewBag.User = user;
            var posts = dbposts.Include(x => x.Topic).Include(x => x.Ratings).Select(x => _mapper.Map<PostVM>(x));
            return View("GetByUsers", posts);
        }
    }
}

WebApp/Controllers/TagController.cs
using AutoMapper;
using Azure;
using Lib.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC.ViewModels;
using NuGet.Protocol;

namespace MVC.Controllers
{

    [Authorize(Roles = "Admin")]
    public class TagController : Controller
    {
        private readonly RwaContext _context; 
        private readonly IMapper _mapper;


        public TagController(RwaContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: TagController
        public ActionResult Index()
        {
            var tags = _context.Tags.Include(x => x.Topics).ThenInclude(x => x.Posts).Select(x => _mapper.Map<TagVM>(x));
            return View(tags);
        }

        // GET: TagController/Details/5
        public ActionResult Details(int id)
        {
            var dbtag = _context.Tags.Include(x=> x.Topics).ThenInclude(x=>x.Posts).FirstOrDefault(x => x.Id == id);
            var tagvm = _mapper.Map<TagVM>(dbtag);
            return View(tagvm);
        }

        // GET: TagController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TagController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TagVM tagvm,string action)
        {
            try
            {
                if (_context.Tags.Any(x=>x.Name==tagvm.Name))
                {
                    ViewBag.ErrorMessage= "Tag with this name already exists.";
                    return View("Create");
                }
                var genre = _mapper.Map<Tag>(tagvm);
                _context.Tags.Add(genre);
                _context.SaveChanges();


                if (action == "Create")
                {
                    return RedirectToAction(nameof(Index));
                    
                }
                return RedirectToAction("Create");

            }
            catch
            {
                return View();
            }
        }

        // GET: TagController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var dbtag = _context.Tags.Include(x => x.Topics).ThenInclude(x => x.Posts).FirstOrDefault(x => x.Id == id);
                var tagVm = _mapper.Map<TagVM>(dbtag);
                return View(tagVm);
            }
            catch (Exception e)
            {

                return View();
            }

        }

        // POST: TagController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, TagVM tag)
        {
            try
            {
                var dbtag = _context.Tags.Include(x => x.Topics).ThenInclude(x => x.Posts).FirstOrDefault(x => x.Id == id);
                dbtag.Name = tag.Name;
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TagController/Delete/5
        public ActionResult Delete(int id)
        {
            var dbtag = _context.Tags.Include(x => x.Topics).ThenInclude(x => x.Posts).FirstOrDefault(x => x.Id == id);
            var tag = _mapper.Map<TagVM>(dbtag);
            return View(tag);
        }

        // POST: TagController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, TagVM tag)
        {
            try
            {
                var dbtag = _context.Tags.Include(x => x.Topics).ThenInclude(x => x.Posts).FirstOrDefault(x => x.Id == id);
                _context.Tags.Remove(dbtag);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <div class="badge bg-primary">User not logged in</div>
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LayoutAdmin.cshtml
@{
    var user = this.ViewContext.HttpContext.User;
    string username = user.Identity.Name;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminHome" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Topics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Users">Users</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout">Log Out</a>
                        <a class="nav-link text-dark" id="usersname"  asp-area="" asp-controller="User" asp-action="Details">@username</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_LayoutUser.cshtml
@{
    var user = this.ViewContext.HttpContext.User;
    string username = user.Identity.Name;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topic" asp-action="Index">Topics </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="GetByUsersString" asp-route-username="@username">My Posts</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Logout">Log Out</a>
                        <a class="nav-link text-dark" id="usersname" asp-area="" asp-controller="User" asp-action="Details">@username</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>